Haiku: Fix R1/beta4 breakage after the previous commit. [skip ci]
./pcap-haiku.c:227:14: error: 'IFT_TUNNEL' undeclared (first use in this
  function); did you mean 'IFT_TUN'?

Also, to avoid unnecessary confusion, ignore the loopback interface as
a capture device on Haiku versions that don't yet have the changes
necessary to make it work.

(cherry picked from commit e1c499b0d13bf975de0d545230369e64b28ec56a)