Squelch Clang warnings about OpenSSL.
SunOS openindiana 5.11 illumos-de27825976 i86pc i386 i86pc

clang version 17.0.6 (https://github.com/OpenIndiana/oi-userland.git
  e8024d02bcf37929f39ab5d7ba1a689029e42ba8)
Target: x86_64-pc-solaris2.11
Thread model: posix
InstalledDir: /usr/bin

In file included from ./sslutils.c:42:
In file included from ./sslutils.h:38:
In file included from /usr/openssl/1.0/include/openssl/ssl.h:156:
In file included from /usr/openssl/1.0/include/openssl/x509.h:87:
/usr/openssl/1.0/include/openssl/ecdsa.h:295:14: error: parameter
  'flags' not found in the function declaration
  [-Werror,-Wdocumentation]
/usr/openssl/1.0/include/openssl/ecdsa.h:301:14: error: parameter
  'ecdsa_method' not found in the function declaration
  [-Werror,-Wdocumentation]
/usr/openssl/1.0/include/openssl/ecdsa.h:302:14: error: parameter
  'name' not found in the function declaration
  [-Werror,-Wdocumentation]

Add a pair of diagnostic control macros for -Wdocumentation and use it
around including OpenSSL headers.

(cherry picked from commit 9a408b9808d38fc60013afa3a06db70a30bbe898)